# Generated by Django 5.0.3 on 2024-03-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
